# Personal
title: Coding Stories
email: airscorp@gmail.com
description: >
  Jekyll blog about my doings and coding woes hosted on github.
twitter_username: nickraptis
github_username:  nickraptis

# External services
disqus_shortname: codingstories
disqus_enable:    true
ga_tracking_id:   UA-55878251-1
ga_enable:        true

# Where things are
#source:      . # not overridable by GitHub
#destination: ./_site
#plugins:     ./_plugins
#layouts:     ./_layouts
#data_source: ./_data
#collections: null

# Handling Reading
#safe:         false
safe: true # not overridable by GitHub
#include:      [".htaccess"]
#exclude:      []
exclude:
- CNAME
- Gemfile
- Gemfile.lock
- README.md
#keep_files:   [".git", ".svn"]
#encoding:     "utf-8"
#markdown_ext: "markdown,mkdown,mkdn,mkd,md"
#textile_ext:  "textile"

# Filtering Content
#show_drafts: null
#limit_posts: 0
#future:      true
#unpublished: false

# Plugins
#whitelist: []
#gems:      []
gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap

# Conversion
#markdown: kramdown
markdown: redcarpet
#highlighter: pygments # overridable by GitHub
highlighter: rouge
#lsi: false # not overridable by GitHub
#excerpt_separator: "\n\n"

# Serving
#detach:  false
#port:    4000
#host:    0.0.0.0
#baseurl: "" # does not include hostname
baseurl: ''
url: 'http://blog.airscorp.gr'

# Backwards-compatibility
#relative_permalinks: false

# Outputting
#permalink: date
permalink: /:year/:month/:day/:title/
#paginate_path: /page:num
paginate_path: /page/:num
#timezone: null
timezone: Europe/Athens

#quiet:    false
#defaults: []
defaults:
  -
    scope:
      path: ''
      type: posts
    values:
      type: post
      layout: post
      disqus: embed
  -
    scope:
      path: ''
      type: pages
    values:
      type: page
      layout: page
  -
    scope:
      path: ''
      type: drafts
    values:
      type: draft
      layout: post

# Markdown Processors
#rdiscount:
#  extensions: []

#redcarpet: # extension docs: http://goo.gl/2GDfmO
#  extensions: []

kramdown:
  input: GFM
#  auto_ids:      true
#  footnote_nr:   1
#  entity_output: as_char
#  toc_levels:    1..6
#  smart_quotes:  lsquo,rsquo,ldquo,rdquo
#  use_coderay:   false

#  coderay:
#    coderay_wrap:              div
#    coderay_line_numbers:      inline
#    coderay_line_number_start: 1
#    coderay_tab_width:         4
#    coderay_bold_every:        10
#    coderay_css:               style

#redcloth:
#  hard_breaks: true

sass:
#  sass_dir: _sass
#  style:    :compact
  #style:    :nested
  #style:    :expanded
  #style:    :compact
  style:    :compressed
